const VENUES = [
  { value: 'abierto-gnp-seguros', label: 'Abierto Gnp Seguros' },
  { value: 'acto', label: 'ACTO' },
  { value: 'algodoneros-de-guasave', label: 'Algodoneros De Guasave' },
  { value: 'alias-testing-prod', label: 'Alias Testing Prod' },
  { value: 'antofest-cemo', label: 'Antofest Cemo' },
  { value: 'antiguo-estadio-akron', label: '(Antiguo)Estadio Akron' },
  { value: 'archipielago', label: 'Archipiélago' },
  { value: 'arena-astros', label: 'Arena Astros' },
  { value: 'atletico-de-san-luis', label: 'Atlético De San Luis' },
  { value: 'auditorio-puebla', label: 'Auditorio Puebla' },
  { value: 'bar-americas', label: 'Bar Americas' },
  { value: 'basura', label: 'Basura' },
  { value: 'boletomovil', label: 'Boletomovil' },
  { value: 'cafetal', label: 'Cafetal' },
  { value: 'calaverandia', label: 'Calaverandia' },
  { value: 'caliente-de-durango', label: 'Caliente De Durango' },
  { value: 'chivas', label: 'Chivas' },
  { value: 'chivasdemo', label: 'Chivasdemo' },
  { value: 'club-atletico-morelia', label: 'Club Atlético Morelia' },
  { value: 'club-de-futbol-america', label: 'Club De Futbol América' },
  { value: 'club-puebla', label: 'Club Puebla' },
  { value: 'copa-yucatan', label: 'Copa Yucatan' },
  { value: 'cruz-azul', label: 'Cruz Azul' },
  { value: 'cybercash', label: 'Cybercash' },
  { value: 'demodmx', label: 'Demodmx' },
  { value: 'demostracion-clientes', label: 'Demostracion Clientes' },
  { value: 'dia-de-campo-aperol', label: 'Día De Campo Aperol' },
  { value: 'dreamfields', label: 'Dreamfields' },
  { value: 'fc-juarez', label: 'Fc Juárez' },
  { value: 'festival-del-chef', label: 'Festival Del Chef' },
  { value: 'fiesta-20-anos-cerveza-minerva', label: 'Fiesta 20 Años Cerveza Minerva' },
  { value: 'foro-boletomovil', label: 'Foro Boletomovil' },
  { value: 'guerreros-de-oaxaca', label: 'Guerreros De Oaxaca' },
  { value: 'hermoso-carino', label: 'Hermoso Cariño' },
  { value: 'hotel-el-ganso', label: 'Hotel El Ganso' },
  { value: 'jaguares-de-nayarit', label: 'Jaguares De Nayarit' },
  { value: 'jardines-de-mexico-1-2', label: 'Jardines De Mexico 1/2' },
  { value: 'jardines-de-mexico-2-2', label: 'Jardines De Mexico 2/2' },
  { value: 'la-concha-acustica', label: 'La Concha Acústica' },
  { value: 'mandala-group', label: 'Mandala Group' },
  { value: 'mexico-open-at-vidantaworld', label: 'Mexico Open At Vidantaworld' },
  { value: 'minerva-2025', label: 'Minerva 2025' },
  { value: 'mulek-mexico', label: 'Mulek Mexico' },
  { value: 'navidalia', label: 'NAVIDALIA' },
  { value: 'naranjeros-de-hermosillo', label: 'Naranjeros De Hermosillo' },
  { value: 'otonofest', label: 'Otoñofest' },
  { value: 'paax', label: 'PAAX' },
  { value: 'pioneros-de-los-mochis', label: 'Pioneros De Los Mochis' },
  { value: 'portamerica-latitudes-2025', label: 'Portamérica Latitudes 2025' },
  { value: 'premier-padel-cancun', label: 'Premier Padel Cancún' },
  { value: 'pro-padel-league', label: 'Pro Padel League' },
  { value: 'reactiva', label: 'Reactiva' },
  { value: 'reset-nye-celebration', label: 'Reset Nye Celebration' },
  { value: 'rieleros-de-aguascalientes', label: 'Rieleros De Aguascalientes' },
  { value: 'riviera-maya-open-mayakoba', label: 'Riviera Maya Open Mayakoba' },
  { value: 'shakira-estadio-luis-pirata-fuente', label: 'Shakira Estadio Luis Pirata Fuente' },
  { value: 'sin-usar', label: 'Sin Usar' },
  { value: 'soccerlife', label: 'Soccerlife' },
  { value: 'spkta', label: 'SPKTA' },
  { value: 'spooky-town', label: 'Spooky Town' },
  { value: 'teatro-estudio-cavaret', label: 'Teatro Estudio Cavaret' },
  { value: 'tecolotes-los-2-laredos', label: 'Tecolotes Los 2 Laredos' },
  { value: 'tepatitlan-fc', label: 'Tepatitlan Fc' },
  { value: 'test-arena-bm', label: 'Test Arena Bm' },
  { value: 'test-auditorio-telmex', label: 'Test Auditorio Telmex' },
  { value: 'test-recinto', label: 'Test Recinto' },
  { value: 'the-blaze', label: 'The Blaze' },
  { value: 'toluca-fc', label: 'Toluca Fc' },
  { value: 'torneo-de-la-amistad', label: 'Torneo De La Amistad' },
  { value: 'toros-tijuana', label: 'Toros Tijuana' },
  { value: 'ultimate-tennis-showdown', label: 'Ultimate Tennis Showdown' },
  { value: 'venados-de-mazatlan-lobodome', label: 'Venados De Mazatlán Lobodome' },
  { value: 'venados-fc', label: 'Venados Fc' },
  { value: 'vidanta-world', label: 'Vidanta World' },
  { value: 'villa-navidena', label: 'Villa Navideña' },
  { value: 'wings-of-gratitude', label: 'Wings Of Gratitude' },
  { value: 'wta-125-queretaro', label: 'Wta 125 Querétaro' },
  { value: 'wta-250-merida-open', label: 'Wta 250 Merida Open' },
  { value: 'wta-500-gdl-open-akron', label: 'Wta 500 Gdl Open Akron' },
  { value: 'wta-500-merida-open', label: 'Wta 500 Merida Open' },
  { value: 'xantoluz', label: 'Xantoluz' },
  { value: 'yaquis-de-obregon', label: 'Yaquis De Obregón' },
  { value: 'yoshi', label: 'Yoshi' },
  { value: 'yoshi-dev', label: 'Yoshi Dev' },
  { value: 'yoshi-itst', label: 'Yoshi Itst' }
];

export default VENUES;